Explicitly generate coverage data file for Codecov
The v1 version of the `codecov/codecov-action` action automatically generated the data file via `coverage xml`, but the
latest v2 does not, which causes it to fail:

```
[2022-01-05T09:53:02.481Z] ['info'] Searching for coverage files...
[2022-01-05T09:53:02.501Z] ['error'] There was an error running the uploader: Error while cleaning paths. No paths matched existing files!
Error: Codecov: Failed to properly upload: The process '/home/runner/work/_actions/codecov/codecov-action/v2.1.0/dist/codecov' failed with exit code 255
```

It also seems better to have full control over the process by doing it explicitly rather than relying on an action which
is used primarily to handle the data upload to Codecov.